import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import MainButton from '../src/components/MainButton';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <div className={styles.wrapper}>
        <div className="container">
          <main className={styles.main}>
            <div className={styles.left}>
              <h2>Web3 Library Network</h2>
              <p className={styles.desc}>
                Decentralized lend&rent platform for paper books based on smart contracts
              </p>
              <MainButton style={{ marginTop: 20 }} title="Find a book" />
            </div>
            <img src="/assets/mainImg.svg" />
          </main>
        </div>
      </div>

      <div className={styles.wrapper}>
        <div className="container">
          <h2 className={styles.allowsTitle}>The platform allows:</h2>
          <div className={styles.allows}>
            <div className={styles.left}>
              <p> - renting paper books for a deposit instead of buying them,</p>

              <p>- earning from lending to the readers books by becoming a host (web3 library), </p>

              <p>
                - and receiving passive income from allowing the host to use your own books for
                lending.
              </p>
            </div>
            <img src="/assets/howworks.svg" />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
